name: stem_club
description: "A STEM CLUB project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^4.0.0
  url_launcher: ^6.1.5
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  video_player: ^2.4.6
  file_picker: ^5.3.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  lottie: ^3.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/onboarding_bg.png
    - assets/images/logo.png
  
  fonts:
    - family: TitilliumWeb
      fonts:
      - asset: assets/fonts/TitilliumWeb-Regular.ttf
      - asset: assets/fonts/TitilliumWeb-Bold.ttf
        weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
